version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bm_network
  billermgmt:
    container_name : billermgmt
    image: es2b/bm-dev:1.20 #dev
#    image: es2b/bm-prod:1.20 #prod
    ports:
      - 8881:8881
    networks:
      - bm_network
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
networks:
  bm_network:
    name: bm_network

